Homework-3  Request #2
mensigo/smart-home-2020 pull request #11
Opened 2020-10-27 16:14 UTC by mensigo

**Поинт**: signalisation/SignalisationImpl.java – Перечитайте про паттерн состояние. Должно быть поле с текущим состоянием. Действия в сигнализации меняют состояния. Клиент сигнализации смотрит на включена ли сигнализация или нет.
**Испра**: поле состояние теперь присутствует явно (а не в виде String, как раньше) и имеет тип SignalState

**Поинт**: events/decorators/EventChooserDecorator.java – В чем смысл этого класса, который выполняет одно действие? Может он лишний и можно просто это действие вызывать в SignalisationEventChooserDecorator?
**Испра**: EventChooserDecorator --переим--> BaseEventHandlerRunnerDecorator, этот класс нужен как точка расширения - над ним надстраиваются другие декораторы (в т.ч. SignalisationEventHandlerRunnerDecorator) - всё как в статье про паттерн Декоратор

**Поинт**: events/decorators/SignalisationEventChooserDecorator.java – Очень сложно и непонятно. KISS принцип. // Здесь должен быть просто вызов делегата (см. паттерн декоратор).
**Испра**: SignalisationEventChooserDecorator --переим--> SignalisationEventHandlerRunnerDecorator, логика одноразовой отправки смс была упрощена, но по-прежнему соответствует требованию "При этом смс-оповещение должно отправляться всего один раз, а не для каждого обработчика." + выделена ответственность отправки смс в SignalisationSMSSender

-- upd --

**Поинт**: objects/SmartHome.java – (про иниц. сигнализации с явным указанием строки-кода) Не используйте строковые литералы в коде. Передавайте все снаружи через конструктор.
**Испра**: инициализация кода убрана в мейн

**Поинт**: signalisation/SignalisationImpl.java – Зачем вы работаете со строками? Зачем тогда вам ООП конструкции Java?
В любом случае вместо строковых констант лучше создать enum с возможными состояниями, чтобы ограничить возможные значения поля и не ошибиться. Это один вариант реализации паттерна состояние.
По 3 заданию мы учимся имплементировать другой вариант - https://refactoring.guru/ru/design-patterns/state. Здесь классы представляют различные состояния и в них находится логика переходов между состояниями.
**Испра**: поинт в большей степени исправлен выше, здесь добавил enum на состояний

2020-11-09 10:02 UTC, a-ivanov requested changes

2020-11-09 10:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/general/Application.java
> +    private final SmartHomeDataInput smartHomeDataInput;
Лишнее поле.

2020-11-09 10:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/signalisation/Signalisation.java
> +    void setState(SignalState state, String enteredCode);
Установка состояния - деталь реализации, лишнее в API.

2020-11-09 10:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/signalisation/DeactivatedSignalState.java
> +    public SignalStateName getName() {
Это лишнее, используйте `state instanceof SpecificSignalState`.

2020-11-09 10:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/signalisation/Signalisation.java
> +    void activate(String enteredCode);
Не надо возвращать состояние наружу и в клиентском коде проверять текущее состояние, скройте это все в новом методе `isAlarmed()`.

2020-11-09 10:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/decorators/SignalisationEventHandlerRunnerDecorator.java
> +public class SignalisationEventHandlerRunnerDecorator extends BaseEventHandlerRunnerDecorator {
`BaseEventHandlerRunnerDecorator` здесь лишний, не надо усложнять наследованием, лучше перенести все в `SignalisationEventHandlerRunnerDecorator`.

2020-11-09 10:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/decorators/SignalisationEventHandlerRunnerDecorator.java
> +            if (signalStateName.equals(STATE_ALARMED)) {
Вся проверка состояний - внутри сигнализации.

2020-11-09 10:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/decorators/SignalisationSMSSender.java
> +public class SignalisationSMSSender implements SMSSender {
Скорее `DummySMSSender`.

2020-11-09 10:03 UTC, a-ivanov commented
Не надо создавать по новому пулл-реквесту на каждое исправление, просто добавляйте изменения в ветку с заданием и пушайте сюда.

2020-11-18 20:38 UTC, mensigo commented on src/main/java/ru/sbt/mipt/oop/general/Application.java
> +    private final SmartHomeDataInput smartHomeDataInput;
убрано поле smartHomeDataOutput

2020-11-18 20:38 UTC, mensigo commented on src/main/java/ru/sbt/mipt/oop/signalisation/Signalisation.java
> +    void setState(SignalState state, String enteredCode);
убраны сеттеры из API сигнализации

2020-11-18 20:39 UTC, mensigo commented on src/main/java/ru/sbt/mipt/oop/signalisation/DeactivatedSignalState.java
> +    public SignalStateName getName() {
класс SignalStateName заменен на instanceof операцию (isAlarmed, isActivated, isDeactivated) в SignalisationImpl

2020-11-18 20:40 UTC, mensigo commented on src/main/java/ru/sbt/mipt/oop/signalisation/Signalisation.java
> +    void activate(String enteredCode);
убран геттер состояния

2020-11-18 20:40 UTC, mensigo commented on src/main/java/ru/sbt/mipt/oop/events/decorators/SignalisationEventHandlerRunnerDecorator.java
> +public class SignalisationEventHandlerRunnerDecorator extends BaseEventHandlerRunnerDecorator {
ликвидирован BaseEventHandlerRunnerDecorator

2020-11-18 20:40 UTC, mensigo commented on src/main/java/ru/sbt/mipt/oop/events/decorators/SignalisationEventHandlerRunnerDecorator.java
> +            if (signalStateName.equals(STATE_ALARMED)) {
+

2020-11-18 20:41 UTC, mensigo commented on src/main/java/ru/sbt/mipt/oop/events/decorators/SignalisationSMSSender.java
> +public class SignalisationSMSSender implements SMSSender {
++

2020-11-19 11:27 UTC, a-ivanov approved these changes

2020-11-19 11:27 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/general/Application.java
> +                application.eventGenerator,
Вот зачем сначала передавать ссылку в поле Application, а потом просто его оттуда передавать в другой класс?
Уберите из Application эти неиспользуемые поля и создайте локальные переменные:
`EventGenerator eventGenerator = new EventGenerator(); ... RunningCycleApplication runCycleApplication = new RunningCycleApplication(eventGenerator, ...)`.

2020-11-19 18:00 UTC, merged