Hometask-4  Request #1
mensigo/smart-home-2020 pull request #12
Opened 2020-10-28 12:03 UTC by mensigo

ru.sbt.mipt.oop.lib.coolcompany – добавлен адаптер на класс SensorEventsManager, а также spring application
ru.sbt.mipt.oop.spring – spring config
ивенты DoorIsUnlocked и DoorIsLocked оставлены без интеграции (в двери), как сторонние (просто выводятся)

2020-11-13 11:24 UTC, a-ivanov requested changes

2020-11-13 11:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/lib/coolcompany/CCEventTypeTranslatorImpl.java
> +        switch (ccEvent.getEventType()) {
Нарушение OCP, см. https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#используйте-фабрики-для-конвертации-событий-внешней-бибилотеки

2020-11-13 11:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/spring/BaseConfig.java
> +    SensorEventsManager createSensorEventsManager() {
В названии бинов по конвенции спринга не используют глаголы.

2020-11-18 22:02 UTC, mensigo commented on src/main/java/ru/sbt/mipt/oop/lib/coolcompany/CCEventTypeTranslatorImpl.java
> +        switch (ccEvent.getEventType()) {
switch из CCEventTypeTranslatorImpl заменен на мапу в CCLibConfig

2020-11-18 22:02 UTC, mensigo commented on src/main/java/ru/sbt/mipt/oop/spring/BaseConfig.java
> +    SensorEventsManager createSensorEventsManager() {
++

2020-11-19 11:37 UTC, a-ivanov requested changes

2020-11-19 11:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/lib/coolcompany/SensorEventsManagerAdapterImpl.java
> +    public SensorEventsManagerAdapterImpl(SensorEventsManager sensorEventsManager,
Адаптер должен адаптировать интерфейс ru.sbt.mipt.oop.lib.coolcompany.EventHandler к вашим обработчикам из предыдущих заданий.
Этот класс делает не то.
У вас должно быть что-то вроде `MyEventHandler implements ru.sbt.mipt.oop.lib.coolcompany.EventHandler {...}`, потом `@Bean SensorEventsManager sensorEventManager(MyEventHandler myEventHandler) { SensorEventManager manager = new SensorEventManager(); manager.registerEventHandler(myEventHandler); return manager;`.

2020-11-19 19:01 UTC, mensigo commented on src/main/java/ru/sbt/mipt/oop/lib/coolcompany/SensorEventsManagerAdapterImpl.java
> +    public SensorEventsManagerAdapterImpl(SensorEventsManager sensorEventsManager,
теперь адаптирован EventHandler (вместо SensorEventsManager, как раньше)

2020-11-20 07:50 UTC, a-ivanov approved these changes

2020-11-20 07:50 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/lib/coolcompany/CCEventTypeTranslatorImpl.java
> +        SensorEventType sensorEventType = ccEventTypeToSensorEventTypeMap.get(ccEvent.getEventType());
Проверка на наличие eventType в мапе.

2020-11-20 22:39 UTC, mensigo commented on src/main/java/ru/sbt/mipt/oop/lib/coolcompany/CCEventTypeTranslatorImpl.java
> +        SensorEventType sensorEventType = ccEventTypeToSensorEventTypeMap.get(ccEvent.getEventType());
++

2020-11-20 22:40 UTC, merged