Hometask-5  Request #1
mensigo/smart-home-2020 pull request #13
Opened 2020-11-04 10:47 UTC by mensigo

- ru.sbt.mipt.oop.lib.remotecontrol.* – добавлена реализация стороннего интерфейса RemoteControl + кнопки в форме паттерна "Команда" + новые action, при этом реализован сценарий, предполагающий обращение кнопки к action'ам напрямую, а не через цепочку ButtonCommand->SensorEvent->EventHandler->Action
- ru.sbt.mipt.oop.spring.RemoteControlConfig – новые пульты могут быть добавлены здесь (для последующей регистрации в SpringApplication)
- при добавлении новой функции кнопки нужно реализовать ButtonCommand и включить в пульт в конфиге
- при добавлении нового кода кнопки нужно просто указать новый buttonCode при создании List<ButtonCommand> в конфиге, при этом предполагается, что ответственность проверки принадлежности кода кнопки набору ABCD1234... находится на стороне сторонней библиотеки (она же регистрирует пульты)
- добавлены тесты на кнопки-реализации ButtonCommand и на пульт-реализацию RemoteControl

2020-11-13 11:34 UTC, a-ivanov requested changes

2020-11-13 11:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/general/SpringApplication.java
> +        RemoteControlRegistry remoteControlRegistry = context.getBean(RemoteControlRegistry.class); // formally for now
Зачем? Достаточно в созданном бине RemoteControlRegistry вызвать registerRemoteControl.

2020-11-13 11:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/spring/RemoteControlConfig.java
> +    SignalisationActivateButtonCommand createSignalisationActivateButtonCommand(String buttonCode,
Как в 4 дз, глаголы в названии бинов по конвенции не используются.

2020-11-13 11:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/spring/RemoteControlConfig.java
> +        Map<String, RemoteControl> rcMap = createRemoteControlWithIdMap(commandSender, smartHome);
Не надо вызывать метод, просто `@Bean RemoteControlRegistry createRemoteControlRegistry(CommandSender commandSender, SmartHome smartHome, Map<String, RemoteControl> rcMap) {...}`.

2020-11-13 11:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/lib/remotecontrol/buttons/ButtonCommand.java
> +    void execute(String buttonCode);
Нет, проверка кода - это ответственность имплементации RemoteControl.

2020-11-20 08:03 UTC, a-ivanov requested changes

2020-11-20 08:03 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/lib/remotecontrol/buttons/ButtonCommand.java
> +    void execute(String buttonCode);
Не сделано. Клиент команды не должен знать деталей ее выполнения, например, выполнено ли условие равенства кода.

2020-11-20 23:51 UTC, mensigo commented on src/main/java/ru/sbt/mipt/oop/general/SpringApplication.java
> +        RemoteControlRegistry remoteControlRegistry = context.getBean(RemoteControlRegistry.class); // formally for now
++

2020-11-20 23:51 UTC, mensigo commented on src/main/java/ru/sbt/mipt/oop/spring/RemoteControlConfig.java
> +    SignalisationActivateButtonCommand createSignalisationActivateButtonCommand(String buttonCode,
++

2020-11-20 23:51 UTC, mensigo commented on src/main/java/ru/sbt/mipt/oop/spring/RemoteControlConfig.java
> +        Map<String, RemoteControl> rcMap = createRemoteControlWithIdMap(commandSender, smartHome);
++

2020-11-20 23:52 UTC, mensigo commented on src/main/java/ru/sbt/mipt/oop/lib/remotecontrol/buttons/ButtonCommand.java
> +    void execute(String buttonCode);
- ответственность проверки кода перемещена из ButtonCommand в RemoteControlImpl
- теперь ButtonCommand.execute() вызывается без параметров

2020-11-23 08:39 UTC, a-ivanov approved these changes

2020-11-23 18:18 UTC, merged